version: "3.3"
services:
  terraform-http-backend:
    image: jspaulsen/terraform-http-backend:v0.1.0-dev.0-amd64
    environment:
      TF_HTTP_USERNAME: "asdf" # "qwYH9QwmmUB4UJ9P"
      TF_HTTP_PASSWORD: "asdf" # "YxNh9bXsb9zcfYRL"
      LOG_LEVEL: DEBUG
    volumes:
      - ./db:/var/lib/terraform-http-backend
