version: "3.3"
services:
  terraform-http-backend:
    image: jspaulsen/terraform-http-backend:v0.1.0-dev.0
    restart: unless-stopped
    environment:
      TF_HTTP_USERNAME: "username"
      TF_HTTP_PASSWORD: "password"
      LOG_LEVEL: INFO
      HTTP_PORT: 8443
    ports:
      - 8443:8443
    volumes:
      - db-data:/var/lib/terraform-http-backend

volumes:
  db-data:
    driver_opts:
      type: none
      device: /var/lib/terraform-http-backend
      o: bind
