version: 2
jobs:
  build-test:
    docker:
      - image: cimg/base:2020.12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Test
          command: ./test.sh
  publish:
    docker:
      - image: cimg/base:2020.12
    steps:
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
      - run:
          name: Publish image
          command: ./build.sh --publish
  publish-arm:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.large
    steps:
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
      - run:
          name: Publish image
          command: ./build.sh --publish


workflows:
  version: 2
  build-master:
    jobs:
      - build-test
      - publish:
          requires:
            - build-test
          filters:
            branches:
              only: develop
      - publish-arm:
          requires:
            - build-test
          filters:
            branches:
              only: develop
